### ISSUE TITLE
Write some unit tests

### ISSUE THREAD

**Issue by bradmsmith** [CompassHB/web#27]
Once I finish the #13, I might take a stab at some unit testing. This is for notes until I write my first unit test.

Need to do more research on these:

* Jest - https://facebook.github.io/jest/docs/tutorial-react.html
* Flux - http://facebook.github.io/flux/docs/testing-flux-applications.html

**Comment by ewinslow** [comment]
We have a few example unit tests already. My vote is to close this and reopen any when we have a clear understanding of the value they would provide.
