### ISSUE TITLE
Flesh out page content

### ISSUE THREAD

**Issue by bradmsmith** [CompassHB/web#32]
Let's copy the HTML from the static pages on the current site into the new site.

**Conversion Tools:**
* HTML to JSX: https://facebook.github.io/react/html-jsx.html
* JSX to Javascript: http://babeljs.io/repl/

For example, the existing content from `https://compasshb.com/ice-cream-evangelism` would go into the `ice-cream-evangelism.ts` file.

**Comment by ewinslow** [comment]
Lots of progress on this. I think it's probably worth it to start reporting separate issues for the individual tasks that remain.
