### ISSUE TITLE
Port data from Laravel to Wordpress

### ISSUE THREAD

**Issue by ewinslow** [CompassHB/web#41]
Wonder if there's a standard import mechanism for WordPress? Otherwise maybe we can just get a few folks together and crank it out manually in an hours' time.

**Comment by bradmsmith** [comment]
I think we can export it as CSV, do some mapping, and use the Wordpress import plugin.

**Comment by bradmsmith** [comment]
FYI. I pointed the domain api.compasshb.com to the WP site.

**Comment by ewinslow** [comment]
Sweet, so I can point to that instead of the plain IP address?

**Comment by bradmsmith** [comment]
Yes

Sent from Outlook<https://aka.ms/qtex0l>




On Sat, Jul 2, 2016 at 3:32 PM -0700, "Evan Winslow" <notifications@github.com<mailto:notifications@github.com>> wrote:

Sweet, so I can point to that instead of the plain IP address?

On Fri, Jul 1, 2016 at 11:47 PM Brad Smith <notifications@github.com> wrote:

> FYI. I pointed the domain api.compasshb.com to the WP site.
>
> -
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/CompassHB/web/issues/41#issuecomment-230087391>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAVw1JoSNfkRCU25_DFF4tVQJfIaBiocks5qRgl5gaJpZM4IbXGd>
> .
>

-

**Comment by bradmsmith** [comment]
I upgraded the ACF WP plugin and custom field names have changed. I don't know if this affects the API or not but here it the change:

```
Changed to class names

Field class names have changed slightly from field_type-{$type} to acf-field-{$type}. This change was introduced to better optimize JS performance.
```

**Comment by ewinslow** [comment]
Hey, are we still planning on doing a full data port? Should that block the transition?

**Comment by bradmsmith** [comment]
This is done. The live site pulls everything from the API and no longer from the old DB.
