### ISSUE TITLE
Document URL structure

### ISSUE THREAD

**Issue by bradmsmith** [CompassHB/web#43]
Work in progress

**Ministries**
Includes: Youth, Men, Women, Kids...

/{ministry}
/{ministry}/{sermons|messages}
/{ministry}/{sermons|messages}/{sermon|message}
/{ministry}/{series}
/ministry}/{series}/{series}

**Comment by ewinslow** [comment]
Maybe we need to rethink how we organize the pages such that we get a list of URLs all in one spot so you can see at a glance what the structure is.

**Comment by ewinslow** [comment]
Like all URLs should be in server.ts
