### ISSUE TITLE
Document API Endpoints

### ISSUE THREAD

**Issue by bradmsmith** [CompassHB/web#49]
*Sermons*
- [ ] https://api.compasshb.com/wp-json/wp/v2/posts?filter[cat]=1&_embed&filter[posts_per_page]

**Comment by ewinslow** [comment]
I created a class: CompassHBWordPress. This has methods for using the various endpoints. If you add stuff there, that will serve as pretty good documentation.

**Comment by ewinslow** [comment]
This now lives in `model/wordpress.ts`. Add more methods/features there as needed!
