### ISSUE TITLE
CMS / Admin container

### ISSUE THREAD

**Issue by bradmsmith** [CompassHB/web#5]
We talked about using Wordpress as a container for the admin. Looking into this, the free hosted version of Wordpress.com will not meet our needs because they limit the ability to use plugins. So we would have to self-host this...

Thinking more about this, it doesn't make sense to me for us to use Wordpress since we want to standardize on JavaScript. Are there any JavaScript/node CMS open source projects we should use? A quick search shows one called KeystoneJS...

**Comment by ewinslow** [comment]
So far we're going with wordpress. Pretty confident this will be flexible enough to support our use-cases.
