### ISSUE TITLE
Set up a staging site so we (and pastors) can easily track progress until port is done

### ISSUE THREAD

**Issue by ewinslow** [CompassHB/web#55]
@bradmsmith I can't remember if you did this already? If not, it'd be great to have a non-live site that has the lastest code until we are able to actually release to the live site.

**Comment by bradmsmith** [comment]
Not yet. I can set this up. Want it to always have the master branch live?

**Comment by ewinslow** [comment]
Yea that'd be perfect!

**Comment by bradmsmith** [comment]
http://three.compasshb.com/

**Comment by ewinslow** [comment]
What is the significance of "three"?

**Comment by bradmsmith** [comment]
```
user@compasshb:~/three.compasshb.com$ pwd
/home/user/three.compasshb.com
user@compasshb:~/three.compasshb.com$ forever start current/_out/server.js -w --watchDirectory /home/forge/three.compasshb.com/
```
