### ISSUE TITLE
Implement replacement service-worker.js and manifest.json

### ISSUE THREAD

**Issue by ewinslow** [CompassHB/web#62]
These two features together will trigger features in Chrome that allow adding to homescreen, fullscreen viewing, offline support, etc. It's basically a way to get an android app without the overhead of going through the play store... We have limited support for it on the current website and I'd hate to lose what we have.

**Comment by ewinslow** [comment]
Also now that we're all JS, there's a good chance we could support a client side routing solution via service worker. That could feel very app-like in terms of performance.

**Comment by bradmsmith** [comment]
Build failing and therefore deploy to staging failed...

**Comment by ewinslow** [comment]
Serves me right for not going through PR flow

**Comment by ewinslow** [comment]
Fixing now...
