### ISSUE TITLE
Easy way for staff to update scripture of the day image

### ISSUE THREAD

**Issue by bradmsmith** [CompassHB/web#66]

**Comment by bradmsmith** [comment]
https://api.compasshb.com/wp-json/compasshb/v1/site_logo/8

**Comment by ewinslow** [comment]
What does `false` refer to there?

**Comment by bradmsmith** [comment]
It's extra output from a WP function we won't use. I had to look it up. See the 'icon' description below.

return wp_get_attachment_image_src( $custom_logo_id , 'full' );

```
Parameters #Parameters

$attachment_id
(int) (Required) Image attachment ID.
$size
(string|array) (Optional) Image size. Accepts any valid image size, or an array of width and height values in pixels (in that order).
Default value: 'thumbnail'
$icon
(bool) (Optional) Whether the image should be treated as an icon.
Default value: false
```

Source: https://developer.wordpress.org/reference/functions/wp_get_attachment_image_src/
