### ISSUE TITLE
Hook up main site pages to live site

### ISSUE THREAD

**Issue by bradmsmith** [CompassHB/web#67]

**Comment by bradmsmith** [comment]
nix the sidebar menu

**Comment by bradmsmith** [comment]
The Visual Composer plugin does not render shortcode via the api. So you get results such as this: https://api.compasshb.com/wp-json/wp/v2/pages?filter[name]=who-we-are

Our work-around will be to add some code to the @compasshb/plugin repository that fixes this issues. The two approaches are:
* On page save, save the rendered HTML into a custom field and expose to the API
* On API call, set a trigger to render the shortcodes

**Comment by bradmsmith** [comment]
Solved this by hooking into the API call, registering the VC shortcodes, and returning the content.

```php
/**
 * Modify REST API content for pages to force
 * shortcodes to render since Visual Composer does not
 * do this
 */
add_action( 'rest_api_init', function ()
{
   register_rest_field(
          'page',
          'content',
          array(
                 'get_callback'    => 'compasshb_do_shortcodes',
                 'update_callback' => null,
                 'schema'          => null,
          )
       );
});

function compasshb_do_shortcodes( $object, $field_name, $request )
{
   WPBMap::addAllMappedShortcodes(); // This does all the work

   global $post;
   $post = get_post ($object['id']);
   $output['rendered'] = apply_filters( 'the_content', $post->post_content );

   return $output;
}
```

**Comment by bradmsmith** [comment]
This is done. There are still some CSS/style issues to match the Visual Composer with what is actually shown on the site -- but the live site now pulls from the WP pages.

**Comment by bradmsmith** [comment]
compasshb/compasshb.com 3f23cf6c346e29a8d367b0c713fa9fc6f3c64314

**Comment by flmuel** [comment]
hey there, in the newest versions of vc its not working for me... am i doing something wrong?

**Comment by jamesdbruner** [comment]
Seconded. I've added that snippet to my functions.php and I'm still seeing `[vc_column_text]` in my response.

**Comment by emranch31** [comment]
Not working for me as well
