### ISSUE TITLE
Port Scripture of the Day (/read)

### ISSUE THREAD

**Issue by ewinslow** [CompassHB/web#69]
- [x] Implement standalone pages for viewing older passages
- [x] Pull logo for homepage from WordPress
- [x] Pull actual Bible text from ESV API
- [x] Pull in Disqus comments
- [x] Parse out the audio from ESV API
- [ ] Pull activity info from Google Analytics

**Comment by bradmsmith** [comment]
For homepage logo.... current Scripture of the Day logo URL is here: https://api.compasshb.com/wp-json/compasshb/v1/site_logo/8 per #66

**Comment by ewinslow** [comment]
@bradmsmith Can you point me to the code for where the TODOs are implemented in the live site?

**Comment by ewinslow** [comment]
E.g., how we get the bible text, how we get disqus comments going, etc.

**Comment by bradmsmith** [comment]
- ESV API: https://github.com/CompassHB/compasshb.com/blob/master/app/Repositories/Scripture/EsvScriptureRepository.php
