### ISSUE TITLE
Project Plan

### ISSUE THREAD

**Issue by bradmsmith** [CompassHB/web#7]
Copying this over from email.

From: Evan Winslow <evan.b.winslow@gmail.com>
Date: Saturday, January 23, 2016 at 5:38 PM
To: Brad Smith <brad@compasshb.com>
Subject: Re: Next steps

Ah yes, one section of the design doc I forgot about was work planning and estimates. Thanks for bringing it up. :). 

To summarize our chat: seems like the main motivation in refactoring the architecture is to make it easier for people to contribute at a level they're comfortable with. It's nice to be able to just jump in and tweak an existing page on the website. You shouldn't have to configure a ton of third party services, vms, etc. just to get going.

As for what to do next in order to get there... This list of tasks assumes we're dropping laravel/php in favor of falcor/node in order to make this happen.

Research a node replacement for Laravel's blade templates.
Create a new branch on the compasshb.com repo for the port to NodeJS
Get www-node talking to api-staging via falcor
Document all pages that need to be ported from blade
Begin porting pages from laravel to node.
Begin adding backend data support to api-staging as needed by frontend port
Document shape of available data on api-staging (e.g. https://gist.github.com/ewinslow/61746875f77786173560)
Delete dummy data in www-node so that it defers to api-staging as new graph endpoints come online.
Configure api-staging to refresh with preset dummy data every day
At this point we'll have reached a milestone where folks should be able to tweak the website pretty easily and use public data from api-staging to render it.
Seems like step 5/6 is where the bulk of the work is. We could maybe set a day aside and see how fast we can crank through that part once 1-4 are done. We can use in-memory Falcor Model as necessary so that porting the frontend templates doesn't block on api-staging being ready.

TBD: Admin area

Unfortunately, we'll still need to decide on what to do about the admin section. That will take some research from you and me I guess. I found some libraries that help with form-building but nothing that goes all the way to wiring up API endpoints and such.

I see a few options:

We could build the thing that generates the forms ourselves. Then at least we're not manually building a bunch of individual forms. But that's still a library we'd have to maintain.
Bite the bullet, don't spend too much time on each form, but just throw them together real quick so we can move forward. Put these in www.compasshb.com.
Find a system that would auto-generate the admin area. Whatever solution we find we'll have to figure out how to wire it up to the unified API server, figure out how authentication is going to work, etc. If it has its own database we'd have to port the existing data to that system. Let me know if you find anything promising in this space.
Thoughts?
On Fri, Jan 22, 2016, 7:30 PM Brad Smith <brad@compasshb.com> wrote:

Thanks!

What is the next step we should do here?

Brad

From: Evan Winslow <evan.b.winslow@gmail.com>
Date: Thursday, January 21, 2016 at 10:31 PM
To: Brad Smith <brad@compasshb.com>

![img_20160121_222705](https://cloud.githubusercontent.com/assets/4544726/13545479/5249e37e-e242-11e5-8fa1-0b6904280435.jpg)

**Comment by ewinslow** [comment]
@bradmsmith Would it make sense to meet up with Bill and reevaluate the plan after assessing the new volunteers' abilities and interests and such?

**Comment by bradmsmith** [comment]
Yes. Let's try to meet before you your trip.

**Comment by ewinslow** [comment]
Seems like we have an agreeable plan that were executing on:

 * Evan works to port everything to Node/Falcor
 * Brad supports this by handling WordPress setup/config
 * Brad makes high-priority tweaks to existing site for short term maintenance
