### ISSUE TITLE
Pull in "Main service" pages' content from wordpress

### ISSUE THREAD

**Issue by ewinslow** [CompassHB/web#70]
* 8 Distinctives
* Giving
* Ice Cream Evangelism
* What We Believe
* Who We Are

**Comment by bradmsmith** [comment]
There is some CSS we need to include in the header for these pages to render correctly.

https://api.compasshb.com/wp-content/plugins/js_composer/assets/css/js_composer.min.css?ver=4.12.1

**Comment by ewinslow** [comment]
Is the ver=4.12.1 going to change frequently? When you upgrade the plugin?
